delivery-conda:
  image: continuumio/miniconda3:4.5.11
  stage: deploy
  only:
    - tags
  script:
    - apt-get update -q -y
    - apt-get install -y build-essential
    - conda config --set always_yes yes --set changeps1 no
    - conda config --add default_channels https://repo.anaconda.com/pkgs/pro
    - conda config --add default_channels https://repo.anaconda.com/pkgs/free
    - conda config --add default_channels https://repo.anaconda.com/pkgs/main
    - conda config --add channels conda-forge
    - conda config --add channels defaults
    - conda config --add channels bioconda
    - conda create -n build anaconda-client conda-build
    - source activate build
    - conda info -a
    - export LINUX_CONDA_FILENAME=$(conda build recipe --output --output-folder build)
    - conda build --no-anaconda-upload --output-folder build recipe
    - conda convert -p osx-64 -o build "$LINUX_CONDA_FILENAME"
    - anaconda -t "$ANACONDA_TOKEN" upload -u transipedia "$LINUX_CONDA_FILENAME"
    - anaconda -t "$ANACONDA_TOKEN" upload -u transipedia "${LINUX_CONDA_FILENAME/linux-64/osx-64}"


delivery-docker:
  image: docker:latest
  services:
    - docker:dind
  stage: deploy
  only:
    - tags
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker pull transipedia/dekupl-viewer || true
    - docker build --pull --cache-from transipedia/dekupl-viewer -t transipedia/dekupl-viewer -t transipedia/dekupl-viewer:$CI_COMMIT_REF_NAME .
    - docker push transipedia/dekupl-viewer
