options(repos='http://cran.rstudio.com/')
install.packages('shiny')
install.packages('shinydashboard')
install.packages('ggplot2')
install.packages('optparse')
install.packages('DT')
install.packages('dendextend')
install.packages('devtools', dependencies = TRUE)
devtools::install_github('andrewsali/shinycssloaders')
source('https://bioconductor.org/biocLite.R'); biocLite('ComplexHeatmap')
install.packages('factoextra')
install.packages('calibrate')